config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'payments/create'

  root 'home#index'
  get '/search' => 'home#search'
  resources :postings do
    resources :comments
    resources :transactions
  end
  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    sessions: 'users/sessions' ,
    registrations: 'users/registrations'
  }

  resources :users, only: [:show, :update, :edit]
  resources :users do 
    member do 
      get "postings", to: "users#postings"
      get "transactions", to: "users#transactions"
        #this route responds to the path defined in form
    end
  end

  resources :payments, only: [:new, :create]

end

app/models/user.rb
class User < ActiveRecord::Base
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	has_many :comments, dependent: :destroy
  	has_many :postings, dependent: :destroy
  	has_many :transactions, dependent: :destroy
    has_many :payments

    mount_uploader :avatar, AvatarUploader

  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]

    # attr_accessible :email, :password,  :remember_me, :avatar, :avatar_cache, :remove_avatar

    # validates_presence_of   :avatar
    # validates_integrity_of  :avatar
    # validates_processing_of :avatar

    def self.from_omniauth(auth)
	  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.first_name = auth.info.name   # assuming the user model has a name
      
	    user.facebook_image = auth.info.image # assuming the user model has an image
      # byebug
	  end
	end

	def self.new_with_session(params, session)
	    super.tap do |user|
	      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
	        user.email = data["email"] if user.email.blank?
	      end
	    end
	end

  def add_credit
    self.credit += 1
    self.save
  end

  def minus_credit
    self.credit -= 1
    self.save
  end


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# omniauth_callbacks_controller.rb

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	 def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super  #super gets the previous page

  end

  def create
    # super
    # @base64_identicon = RubyIdenticon.create_base64("RubyIdenticon", grid_size: 7, square_size: 30, background_color: 0xf0f0f0ff, key: SecureRandom.hex(13))
    
    build_resource(sign_up_params)
    resource.identicon = RubyIdenticon.create_base64("RubyIdenticon", grid_size: 7, square_size: 30, background_color: 0xf0f0f0ff, key: SecureRandom.hex(13))
    # byebug
    resource.save
    
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end  


  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
  	@user = User.find(params[:id])
    # @base64_identicon
  end

  def edit
  	@user = current_user
  end

  def update
  	@user = User.find(current_user.id)
  	if @user.update(user_params)
  		bypass_sign_in(@user)
  		redirect_to root_path
  	else 
  		render "edit"
  	end
  end

  def transactions

    @user = User.find(params[:id])
    
    
  end

  def postings
  end

  private
  def user_params
  	params.require(:user).permit(:password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- edit.html.erb -->
<h1> User Change password page</h1>

<%= form_for(@user, :url => { :action => "update" }, :html => {:multipart => true} ) do |f| %>

  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
    <% f.hidden_field :avatar_cache %>
  </div>

  <div class="field">
    <%= f.label :password, "Password" %><br />
    <%= f.password_field :password, :autocomplete => "off"  %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="action_container">
    <%= f.submit %>
  </div>
<% end %>

	<%= link_to "Back", :back %>

app/views/users/postings.html.erb
<!-- postings.html.erb -->

<div class="row text-center head-pad">
		<h1>Things I've Posted</h1>
</div>

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="panel panel-default">
         <div class="panel-heading map" id="show">

					<% current_user.postings.each do |posting| %>
						<div class="media">
							

								<div class="media-left">
									<a  href="/postings/<%=posting.id%>">
										<%= image_tag (posting.avatars.first.profile.url) unless posting.avatars.first.nil? %>
									</a>
								</div>
							

							<div class="media-body">
								<h3 class="k"><strong><%= posting.title %></strong></h3>
								<p><strong>Posting ID:</strong><br> <%= posting.id %></p>
								<p><strong>Description</strong><i><br>	<%= posting.description %></i></p>
								<p><strong>Address</strong><i><br>	<%= posting.full_address %></i></p>
								<p><strong>Category</strong><i><br><%= posting.category %></i></p>
								<p><strong>Condition</strong><br><i><%= posting.condition %></i></p>

							</div>

							
						</div> <!-- close media -->
					<% end %>

				</div>
			</div>
		</div>
	</div>

app/views/users/show.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default"> 

      <div class="panel-heading-title post_image text-center">
        <h2><%= @user.first_name%> <%=@user.last_name%></h2><br>

        <p>
        <% if @user.avatar.file.nil?  %>
					<% if @user.facebook_image.nil? %>
				 			<img src='data:image/png;base64,<%=@user.identicon %>' class="img-thumbnail">
				 	<% else %> 
				 			<%= image_tag(@user.facebook_image) %>
				 	<% end %>
				<% else %> 
						<%= image_tag(@user.avatar_url(:profile))%>
				<% end %>
			 	</p>
			</div>

			<div class="panel-body">

					<p>
						<strong>User ID</strong><br>
			  		<i><%=@user.id%></i>
		  		</p>

		  		<p>
						<strong>Phone No.</strong><br>
			  		<i><%=@user.phone_no%></i>
		  		</p>

		  		<p>
						<strong>Email</strong><br>
			  		<i><%=@user.email%></i>
		  		</p>
		  	
		  		<p>
						<strong>Credit Standing</strong><br>
			  		<i><%=@user.credit%></i>
		  		</p>

		  		<p>
						<strong>Account Type</strong><br>
			  		<i><%=@user.account_type.capitalize%>
			  			
			  		</i>
		  		</p><br>

	   		<!-- <div class="btn-group pull-right"> -->
	   			
	   			<% if @user.payments.where(status: :authorized).count == 0%>
				    <%= link_to 'Upgrade to Premium' , new_payment_path + "?id=" + @user.id.to_s, class: "btn btn-default btn-block", style: "background-color:green;" %>
				    <% else %>
				    	<span class="btn btn-default">Paid</span>
				    <% end %>
				    <br>
				<%=link_to "Edit", edit_user_registration_path %>
			<!-- </div> -->

app/views/users/transactions.html.erb
<div class="row text-center head-pad">
		<h1>My Transactions</h1>
</div>



 <div class="row">
		<div class="col-md-8 col-md-offset-2">
	
			<% current_user.transactions.each do |transaction| %>
				<div class="panel panel-default">
					<div class="panel-heading map" id="show">
						<div class="media">
							<a href="/postings/<%=transaction.posting.id%>/transactions/<%=transaction.id%>">

								<div class="media-left">
									<%= image_tag (transaction.posting.avatars.first.medium.url) %>
								</div>

								<div class="media-body">
									<h3 class="k"><strong>Posting Title: <%= transaction.posting.title %></strong></h3>
									Transaction ID: <%= transaction.id %><br>
									<%= transaction.posting.description %>
									<% if transaction.success == false %>
					        			<%= form_for(transaction, url: posting_transaction_path(transaction.posting.id,  transaction.id), html: {method: "patch"}) do |f| %>
								        	<%= f.hidden_field :success, :value => true %>
								        	<%= f.hidden_field :status, :value => false %>
								        	<%= f.submit "Confirm transaction.", class: "btn btn-xs btn-primary" %>
					        			<% end %>
				        			<% end %>
								</div>
							</a>
			       		</div> <!-- close media -->
			     	</div> <!-- close heading -->
			    </div> <!-- close panel -->
			<% end %>
	
		</div> <!-- close column -->
	</div> <!-- close row -->

	