config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'payments/create'

  root 'home#index'
  get '/search' => 'home#search'
  resources :postings do
    resources :comments
    resources :transactions
  end
  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    sessions: 'users/sessions' ,
    registrations: 'users/registrations'
  }

  resources :users, only: [:show, :update, :edit]
  resources :users do 
    member do 
      get "postings", to: "users#postings"
      get "transactions", to: "users#transactions"
        #this route responds to the path defined in form
    end
  end

  resources :payments, only: [:new, :create]

end

app/models/posting.rb
class Posting < ActiveRecord::Base
	belongs_to :user
	has_many :transactions, dependent: :destroy
	has_many :comments, dependent: :destroy
	validates :title, presence: true
	validates :description, presence: true
	validates :condition, presence: true
	validates :category, presence: true
	validates :avatars, presence: true 
	validates :city, presence: true
	validates :state, presence: true
	validates :zipcode, zipcode: true
	validates :zipcode, zipcode: { country_code: :my }
	validates :zipcode, zipcode: { country_code_attribute: :zipcode }
	geocoded_by :full_address
	after_validation :geocode, if: ->(posting){ self.full_address.present? and self.full_address_changed? }

	mount_uploaders :avatars, AvatarUploader
	skip_callback :commit, :after, :remove_previously_stored_avatars!

	include PgSearch 
	pg_search_scope :search_by_location, :against => [:address1, :address2, :city, :state, :zipcode]
	pg_search_scope :search_by_category, :against => [:category]
	pg_search_scope :search_by_others, :against => [:title, :description, :condition]
	pg_search_scope :search_any_word, :against =>[:address1, :address2, :city, :state, :zipcode, :title, :description, :condition, :category], :using => {:tsearch => {:any_word => true}}

	def full_address
		[address1, city, state, zipcode].join(', ')
		# [address1, address2, city, state, zipcode].join(', ')
	end

	def full_address_changed?
		attrs = %w{address1 address2 city state zipcode}
		attrs.any?{|a| send "#{a}_changed?"}
	end

	def country_alpha2
	end

	def available?
		if self.availability == true then
			true
		else
			false
		end
	end

end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_action :set_posting, only: [:show, :edit, :update, :destroy]

  # GET /postings
  # GET /postings.json
  def index
    @postings = Posting.all
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
    @comment = Comment.new 
    @transaction = Transaction.new
  end

  # GET /postings/new
  def new
    @posting = Posting.new
  end

  # GET /postings/1/edit
  def edit
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = current_user.postings.new(posting_params)
    respond_to do |format|
      if @posting.save
        format.html { redirect_to @posting, notice: 'Posting was successfully created.' }
        format.json { render :show, status: :created, full_address: @posting }
      else
        format.html { render :new }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postings/1
  # PATCH/PUT /postings/1.json
  def update
    respond_to do |format|
      if @posting.update(posting_params)
        format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
        format.json { render :show, status: :ok, full_address: @posting.full_address }
      else
        format.html { render :edit }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting.destroy
    respond_to do |format|
      format.html { redirect_to postings_url, notice: 'Posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posting
      @posting = Posting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posting_params
      params.require(:posting).permit(:title, :location,:description, :condition, :category, :address1, :address2, :city, :state, :zipcode, :availability,{avatars:[]})
    end
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/postings/_form.html.erb
<%= form_for @posting do |f| %>
  <% if @posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

      <ul>
        <% @posting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<form>
  <div class="form-group">
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
  </div>
  </div>

  <div class="form-group">
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  </div>

  <div class="form-group">
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.select(:condition, ['-','New', 'Like New', 'Fair', 'Salvage'])%>
  </div>
  </div>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.select(:category, ['-', 'Appliances', 'Books', 'Furniture', 'Gadgets', 'Toys','Others'])%>
  </div>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address1, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :state %><br>
    <%= f.select(:state, ['-','Penang', 'Selangor', 'Johor', 'Melaka', 'Perak','Kedah','Pahang','Terengganu','Kelantan','Perlis','Negeri Sembilan', 'Sabah', 'Sarawak', 'Kuala Lumpur'])%>
  </div>


  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode, class: "form-control" %>
  </div>
  
  <br>
  <div>
    <%= f.file_field :avatars, multiple: true %>
  </div>

  <br>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>

<% end %>

</form>
<br>

app/views/postings/edit.html.erb
<div class="push">
  <div class="col-md-6 col-md-offset-3">
    <div class="row">
      <div class="panel panel-default">

        <div class="panel-heading-title"><h2>Edit Post</h2></div>
          <div class="panel-body">

            <%= render 'form' %>

            <%= link_to 'Show', @posting %> |
            <%= link_to 'Back', postings_path %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/postings/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid"> <!-- has to be fluid --> 

  <!-- <div class="module"> -->
    <div class="row row-centered">
      <div class="col-md-12">
        <%= form_tag search_path, method: :get do %>
          <form class="form-inline">
            <div class="form-group col-md-3 col-md-offset-1">
              <%= text_field_tag :location, params[:location], placeholder: "Location", class: "form-control", style: "border-radius:6px;" %>
            </div>
        
            <div class="form-group col-md-3">
              <%= text_field_tag :category, params[:category], placeholder: "Category", class: "form-control", style: "border-radius:6px;" %>
              <%# select("params", "category", Posting::Category, { include_black: true }) %>
            </div>

            <div class="form-group col-md-3">
              <%= text_field_tag :others, params[:others], placeholder: "Description", class: "form-control", style: "border-radius:6px;" %>
            </div>

            <%= submit_tag "Search", class: "btn btn-md btn-primary col-md-1", id: "search-posting" %>
          </form>
        <% end %>
      </div>
    </div>
 <!-- </div> -->

  <div class="row" id="row">  
   <!-- <div class="col-xs-6 col-md-3">
    <div id="pins">
      <div class="thumbnail"> -->

      <% @postings.each do |posting| %>
        <%# if posting.availability && current_user.id != posting.user_id %>
        <% if posting.availability %>

      <div class="col-md-4 module"> <!-- has to be inside so that 3 pins appear in a row-->
        <div id="pins">
          <div class="thumbnail">

            <div class="panel panel-default box grow-posting">

            <div class="panel-heading post_image text-center map">
            <a href="/postings/<%=posting.id%>">
              <%= image_tag posting.avatars.first.medium.url unless posting.avatars.first.nil? %>
            </a>
            </div>
                <!-- <div class=caption""> -->
                <div class="panel-body posting-styling">
                  <h3><%= posting.title %></h3>
                    <span class="thumb-font"><strong>Description</strong><br><%= posting.description %></span><br><br>
                    <span class="thumb-font"><strong>Condition</strong><br><%= posting.condition %></span><br><br>
                    <span class="thumb-font"><strong>Category</strong><br><%= posting.category %></span><br><br>
                    <span class="thumb-font"><strong>Address</strong><br><%= posting.full_address %></span>      
                      
                      <!-- <p>
                      <a href="#" class="btn btn-success" role="button">Get!</a> 
                      <a href="#" class="btn btn-default" role="button">Book!</a>
                      </p> -->
                </div> <!-- close panel body --> 
                <!-- </div> -->  <!-- close caption --> 
            </div> <!-- close panel panel-default --> 

          </div> <!-- close thumbnail --> 
        </div> <!-- close pins --> 
      </div> <!-- close column --> 

        <% end %>
      <% end %> 

      <!-- </div>  --> <!-- close thumbnail -->
    <!-- </div> --> <!-- close column -->
  <!-- </div>  --><!-- close pins -->
  </div> <!-- close row -->
</div> <!-- close container -->

      <script src="https://unpkg.com/scrollreveal@3.3.2/dist/scrollreveal.min.js"></script>
  <script>  
    window.sr = ScrollReveal({ duration: 2000}, 500);
    sr.reveal('.module');
  </script>

app/views/postings/new.html.erb
<div class="push">
  <div class="col-md-6 col-md-offset-3">
    <div class="row">
      <div class="panel panel-default">

        <div class="panel-heading-title"><h2>New Posting</h2></div>
          <div class="panel-body">

              <%= render 'form' %>

              <%= link_to 'Back', postings_path %>
            </div>

      </div>
    </div>
  </div>
</div>

app/views/postings/show.html.erb
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div class="container">

 <!--  <p id="notice"><%= notice %></p> -->

  <!-- <div class="container"> -->
    <div class="col-md-8 col-md-offset-2">
      <!-- <div class="row row-centered"> -->
        <div class="panel panel-default">

            <div class="panel-heading post_image text-center map">
              <% @posting.avatars.each do |x| %>
                <%= image_tag x.medium.url, :style => "width:100%" %>
              <%end%>

            <p>
            <div class="row m">
              <!-- <div class="col-md-6"> -->

            <div class="btn-group pull-right">


              <% if current_user.id != @posting.user.id %>
                <%= form_for(@transaction, url: posting_transactions_path(@posting.id), html: {method: "post"}) do |f| %>
                  <%= f.hidden_field :availability, :value => false %>
                  <%= button_tag(type: 'submit', class: "btn btn-default") do %>
                    <i class="glyphicon glyphicon-shopping-cart"></i> Get!
                  <% end %>
                <% end %>
              <% end %>

             </div>

             <div class="btn-group pull-left">
              <% if current_user.id == @posting.user.id %>
                <%= link_to 'Edit', edit_posting_path(@posting), class: "btn btn-default" if user_signed_in?%>
                <%= link_to 'Destroy', posting_path(@posting), class: "btn btn-default", method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
              <%= link_to 'Back', postings_path, class: "btn btn-default" %>
            </div>


           <!--  </div> -->
            </div>
            </p>

            </div>


            <div class="panel-body">

            <p>
              <strong>Posted by:</strong><br>
              <i><%= @posting.user.first_name %></i>
            </p>

            <p>
              <strong>Title:</strong><br>
              <i><%= @posting.title %></i>
            </p>

            <p>
              <strong>Description:</strong><br>
              <i><%= @posting.description %></i>
            </p>

            <p>
              <strong>Condition:</strong><br>
              <i><%= @posting.condition %></i>
            </p>

            <p>
              <strong>Category:</strong><br>
              <i><%= @posting.category %></i>
            </p>

            <p>
              <strong>Location:</strong><br>
              <i><%= @posting.full_address %></i>
            </p>

            <p>
            <strong>Availability:</strong><br>
            <i><%= @posting.available? %></i>
            </p>
            </div>



                <div class="map">
              <div style='width: 800px;'>
                <div id="map" style='width: 968px; height: 400px;'></div>
              </div>


              <script type="text/javascript">
                handler = Gmaps.build('Google');
                handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
                  markers = handler.addMarkers([
                    {
                      "lat": <%= @posting.latitude %>,
                      "lng": <%= @posting.longitude %>,
                      "picture": {
                      "url": "http://icons.iconarchive.com/icons/paomedia/small-n-flat/32/map-marker-icon.png",
                        "width":  36,
                        "height": 36
                      },
                      "infowindow": "I'm here!"
                    }
                  ]);
                  handler.bounds.extendWith(markers);
                  handler.fitMapToBounds();
                });
              </script>
             </div>

             
  <!-- <p>
    <strong>Availability:</strong>
    <%= @posting.availability %>
  </p> -->

  <!-- COMMENTS SECTION -->


            <div class="panel-footer">
              <% @posting.comments.each do |input| %>
                <%= input.user.email %>
                <%= time_ago_in_words(input.created_at) %><br>
                <%= input.comment %><br>
                <% if input.user_id == current_user.id %>
                  <%= link_to 'Edit', edit_posting_comment_path(input.posting_id, input.id) %>
                  <%= link_to 'Delete', posting_comment_path(input.posting_id, input.id), method: :delete, data: { confirm: 'Are you sure?' } %><br>
                <% end %>
              <% end %>

              <% if user_signed_in? %>
                <%= render 'comments/form' %>
            <% end %>

            
          </div>

        </div>
      <!-- </div> -->
    </div>
  <!-- </div> close container inside -->
  <br>