config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  get 'payments/create'

  root 'home#index'
  get '/search' => 'home#search'
  resources :postings do
    resources :comments
    resources :transactions
  end
  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    sessions: 'users/sessions' ,
    registrations: 'users/registrations'
  }

  resources :users, only: [:show, :update, :edit]
  resources :users do 
    member do 
      get "postings", to: "users#postings"
      get "transactions", to: "users#transactions"
        #this route responds to the path defined in form
    end
  end

  resources :payments, only: [:new, :create]

end

app/views/layouts/_footer.html.erb
<footer class="text-center row">
  <p>
    <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
      <span class="glyphicon glyphicon-chevron-up"></span>
    </a>
  </p>

  <div class="container">
    <a class="btn btn-social-icon btn-twitter">
      <span class="fa fa-twitter"></span>
    </a>
    <a class="btn btn-social-icon btn-facebook">
      <span class="fa fa-facebook"></span>
    </a>
    <a class="btn btn-social-icon btn-google">
      <span class="fa fa-google"></span>
    </a>
    <a class="btn btn-social-icon btn-instagram">
      <span class="fa fa-instagram"></span>
    </a>
  </div>	

  <p>
    TreasureTrash All Rights Reserved 2016 <br>
    Developed by Team 5, August Intake, Next Academy
  </p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">TreasureTrash</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><%= link_to "Post Item", new_posting_path %></li>
      </ul>
      <form class="navbar-form navbar-left" action= "/search" method= "get", >
        <div class="input-group" style="width: 750px">
          <input type="text" class="form-control" name="any">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-default">Search</button>
          </span>
        </div>
        
      </form>
    <% if user_signed_in? %>    
      <ul class="nav navbar-nav navbar-right" style="margin-right: 0px">
	      <li class=""> <%= link_to ("Credits: " + current_user.credit.to_s), user_path(current_user) %></li>
        <%= image_tag (current_user.avatar.nav_avatar.url.to_s), class: "img-circle pull-left"%>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.first_name%> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Profile", user_path(current_user)%></li>
            <li><%= link_to "Transactions", transactions_user_path(current_user)%></li>
            <li><%= link_to "Postings", postings_user_path(current_user)%></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
          </ul>
        </li>
       <%else %>
	      <ul class="nav navbar-nav navbar-right">
	          <li><%= link_to "Login", new_user_session_path unless user_signed_in? %></li>
	          <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path unless user_signed_in? %></li>
          </ul>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head> 
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<!--   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
 -->  
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister|Raleway:300" rel="stylesheet">
  <title>TreasureTrash</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="//maps.google.com/maps/api/js?key=<%=ENV["google_api"]%>"></script>
</head>

<body>


<%= render partial: "layouts/navbar" %>
  

 <span class="alert">
    <%= notice %>
    <%= alert %>
  </span> 
  <section class="row">
    <%= yield %>
  </section>

  <%= render partial: "layouts/footer"%>



  <script src="https://unpkg.com/scrollreveal@3.3.2/dist/scrollreveal.min.js"></script>
  <script>  
    window.sr = ScrollReveal({ duration: 2000 });
    sr.reveal('.module');
  </script>



</body>
</html>